version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sumaxia-app:prod
    container_name: sumaxia_app_prod
    restart: unless-stopped
    working_dir: /var/www
    # Sin mapeo de código: la imagen contiene el proyecto y assets compilados
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=sumaxia
      - DB_USERNAME=sumaxia_user
      - DB_PASSWORD=sumaxia_password
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sumaxia

  mysql:
    image: mysql:8.0
    container_name: sumaxia_mysql_prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sumaxia
      MYSQL_USER: sumaxia_user
      MYSQL_PASSWORD: sumaxia_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - sumaxia

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sumaxia_phpmyadmin_prod
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sumaxia

networks:
  sumaxia:
    driver: bridge

volumes:
  mysql_data:
    driver: local